###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Yoltzin Dominguez Chimal",
    "age": 17,
    "email": "yoltzin.dominguez@hotmail.com"
} 

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/65c1749a7596258531066f70 HTTP/1.1

###
PUT http://localhost:9000/api/users/65c1692e9d77dbb58cea492c HTTP/1.1
Content-Type: application/json

{
    "name": "Oswaldo Raul Dominguez Chimal",
    "age": 22,
    "email": "oswaldo.do-ch@hotmail.com"
} 

###
DELETE  http://localhost:9000/api/users/65c168ba9d77dbb58cea492a HTTP/1.1