###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "rol": "Administrador",
    "nombreCompleto": "Oswaldo Raul Dominguez Chimal",
    "correo": "oswaldo.dominguez@hotmail.com",
    "contrasenia": "oswis123",
    "fechaDeNacimiento": "2001-02-05",
    "genero": "Masculino"
}

###
GET http://localhost:9000/api/users HTTP/1.1 

###
GET http://localhost:9000/api/users/65c59813bbbd205c5406391e HTTP/1.1

###
PUT http://localhost:9000/api/users/65c423f18b3f3729f30d63f3 HTTP/1.1
Content-Type: application/json

{
    "rol": "Administrador",
    "nombreCompleto": "Oswaldo Raul Dominguez Chimal",
    "correo": "oswaldo.dominguez@hotmail.com",
    "contrasenia": "oswis123",
    "fechaDeNacimiento": "2001-02-05",
    "genero": "Masculino"
} 

###
DELETE  http://localhost:9000/api/users/65c59813bbbd205c5406391e HTTP/1.1

###
GET http://localhost:9000/api/recover-password/oswaldo.dominguez@hotmail.com HTTP/1.1


###
POST http://localhost:9000/api/ HTTP/1.1
header name: header value

content