###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "rol": "Usuario",
    "nombreCompleto": "Yoltzin Dominguez Chimal",
    "correo": "yoltzin.dominguez@hotmail.com",
    "contrasenia": "contrasenaSegura123",
    "fechaDeNacimiento": "2007-01-01",
    "genero": "Femenino"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/65c1749a7596258531066f70 HTTP/1.1

###
PUT http://localhost:9000/api/users/65c1692e9d77dbb58cea492c HTTP/1.1
Content-Type: application/json

{
    "name": "Oswaldo Raul Dominguez Chimal",
    "age": 22,
    "email": "oswaldo.do-ch@hotmail.com"
} 

###
DELETE  http://localhost:9000/api/users/65c421b1d292e397b37f83fa HTTP/1.1